set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g detach-on-destroy off   # don't exit from tmux when closing a session
set -g history-limit 1000000   # increase history size (from 2,000)
set -g renumber-windows on     # renumber all windows when any window is closed

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# Command for refreshing the settings
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded tmux config"

set-option -g update-environment "ALACRITTY_LOG \
                                  ALACRITTY_WINDOW_ID \
                                  ALACRITTY_SOCKET"
                
background="#282828"
forground="#ebdbb2"
red_dark="#cc241d"
red_light="#fb4934"
green_dark="#98971a"
green_light="#b8bb26"
yellow_dark="#d79921"
yellow_light="#fabd2f"
blue_dark="#458588"
blue_light="#83a598"
purple_dark="#b16286"
purple_light="#d3869b"
aqua_dark="#689d6a"
aqua_light="#8ec07c"
gray="#a89984"

set -g status "on"
set -g status-position top
set -g status-left-length 100
set -g status-style "fg=${forground},bg=default"
set -g status-left "#[fg=${green_dark},bold]󰚩 #S#[fg=${forground},nobold] | "
set -g status-right ""
set -g window-status-current-format "#[fg=${yellow_dark},bold] 󰋇 #[underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g message-style "fg=${forground},bg=default"
set -g mode-style "fg=${background},bg=${green_dark}"
