set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.config/tmux/tmux.conf
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g detach-on-destroy off   # don't exit from tmux when closing a session
set -g history-limit 1000000   # increase history size (from 2,000)
set -g renumber-windows on     # renumber all windows when any window is closed
set -g status-interval 3       # update the status bar every 3 seconds
set -g status-position top     # macOS / darwin style

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# bind -n M-e display-popup -E "~/.dotfiles/scripts/__kill_tmux_session.sh"
# bind -n M-t display-popup -E "~/.dotfiles/scripts/__list_tmux_sessions.sh"

# Switch to another session if it exists on last window close
set-option -g detach-on-destroy off

# Command for refreshing the settings
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded tmux config"

set-option -g update-environment "ALACRITTY_LOG \
                                  ALACRITTY_WINDOW_ID \
                                  ALACRITTY_SOCKET"
# Tokyonight Moon theme colors
thm_bg="#3c3836"
thm_fg="#ebdbb2"
thm_cyan="#fabd2f"
thm_black="#1d2021"
thm_gray="#a89984"
thm_magenta="#b16286"
thm_pink="#cc241d"
thm_red="#cc241d"
thm_green="#98971a"
thm_yellow="#d79921"
thm_blue="#458588"
thm_orange="#d65d0e"
thm_black4="#665c54"

# Status bar
set -g status "on"
set -g status-bg "${thm_bg}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# Messages
set -g message-style "fg=${thm_fg},bg=${thm_gray},align=centre"
set -g message-command-style "fg=${thm_fg},bg=${thm_gray},align=centre"

# Panes
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_fg}"

# Windows
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-separator ""
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"

# Statusline - current window
set -g window-status-current-format "#[fg=${thm_yellow},bg=${thm_bg}] #I:#[fg=${thm_yellow},bg=${thm_bg}]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=${thm_magenta},bg=${thm_bg}]"

# Statusline - other windows
set -g window-status-format "#[fg=${thm_fg},bg=${thm_bg}] #I: #[fg=${thm_fg},bg=${thm_bg}]#W"

# Statusline - right side
set -g status-right "#[fg=${thm_green},bg=${thm_bg},nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_green},nobold,nounderscore,noitalics] #[fg=${thm_fg},bg=${thm_black4}] #W #{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_cyan}]}#[bg=${thm_black4}]#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_cyan}]}#[fg=${thm_bg}] #[fg=${thm_fg},bg=${thm_black4}] #S "

# Statusline - left side (empty)
set -g status-left ""

# Modes
set -g clock-mode-colour "${thm_fg}"
set -g mode-style "fg=${thm_fg} bg=${thm_black4} bold"
